### ISSUE TITLE
consensus script no longer works

### ISSUE THREAD

**Issue by sdwfrost** [veg/BioExt#21]
1. [ConsensusCore](https://github.com/PacificBiosciences/ConsensusCore) needs to be installed separately; could this be done automagically on install?
2. ConsensusCall no longer as an attribute PoaConfig so `consensus` no longer works.

**Comment by sdwfrost** [comment]
Dear @stevenweaver 

Thanks for updating this issue. I've tried working round the newer ConsensusCore API, but haven't got it running yet; I've tried a bunch of variants. Current script below:

```python
def _consensus(reads, quiver):
    match_ = 0
    mismatch_ = -1
    ins_ = -11
    del_ = -1

    poa_config = cc.AlignConfig(cc.AlignParams(match_,mismatch_,ins_,del_),USE_LOCAL_ALIGNMENT)

    consensus = cc.PoaConsensus.FindConsensus(
        reads,
        poa_config
        ).Sequence()

    if quiver:
        qv_config = cc.QuiverConfig(
            cc.QvModelParams(*NoQVsModelParams.values()),
            cc.ALL_MOVES,
            cc.BandingOptions(4, 5),
            -12.5
            )

        mms = cc.SparseSseQvMultiReadMutationScorer(qv_config, consensus)

        for read in reads:
            mms.AddRead(extractFeatures(read), cc.FORWARD_STRAND)

        consensus, _ = refineConsensus(mms, QV_NITER)

    return consensus
```

**Comment by stevenweaver** [comment]
Dear @sdwfrost, 

Apologies for the delay in response to this issue. In response to (1), ConsensusCore has a number of dependencies outside of Python. Even within `GenomicConsensus`, dependencies for `ConsensusCore` and `ConsensusCore2` are commented out due to integration being ["unnecessarily hard"](https://github.com/PacificBiosciences/GenomicConsensus/blob/d99566a5539f3b44e351c8724ba24aafad7aa0e7/setup.py#L6-L10). There are bioconda packages available for both `ConsensusCore` and `ConsensusCore2`. I believe using them would be the desired route. 

https://anaconda.org/bioconda/python-consensuscore
https://anaconda.org/bioconda/python-consensuscore2

Please note that consensuscore2 is only compatible with linux and python2.

I've come to the conclusion that `FindConsensus` provided by `ConsensusCore` is no longer supported. @nlhepler, the original developer of the script and still very active within PacBio, does not make use of the function `FindConsensus` provided by ConsensusCore. Instead, he uses `FindConsensus` from ConsensusCore2. Please see (this line)[https://github.com/PacificBiosciences/GenomicConsensus/blame/951d120abe5f0c15bf90fe5f2cce74aa4b830be7/GenomicConsensus/arrow/utils.py#L11] and (this line)[https://github.com/PacificBiosciences/GenomicConsensus/blame/951d120abe5f0c15bf90fe5f2cce74aa4b830be7/GenomicConsensus/arrow/utils.py#L412]. 

It appears that in order to fix this script, we will need to move it out of BioExt and into its own repository. Then we will need to downgrade to Python 2. 


Best,
Steven

**Comment by nlhepler** [comment]
An addendum to this: https://github.com/Pacificbiosciences/unanimity is the source for the ConsensusCore2 code, and can be modified to work on python3 without much difficulty (I think the meson build script declared dependencies would need to be changed).

@sdwfrost, let me know if building a bioconda package for you would be of assistance.

**Comment by sdwfrost** [comment]
Back on this now - @nlhepler it would be great if there was a Python3 version to find a consensus for messy data like PacBio.
