### ISSUE TITLE
bealign codon-aware 

### ISSUE THREAD

**Issue by antoine4ucsd** [veg/BioExt#47]
Hello Steve,
I am trying to optimize alignment of HIV env sequences. I started comparing mafft and bealign but I got confusing results.
If I use mafft alignment as an input and run
```
bealign -r HXB2_env    -m HIV_BETWEEN_F  id2.v1.fasta id2.v1.bam
bam2msa id2.v1.bam id2.v2.fas
```
the sequences in v2 versus v1 are NOT identical ,regardless of the gaps. 
this is probably something I am missing
hivalign seems to omit/exclude some regions...

thank you!

![Screen Shot 2022-11-21 at 2 02 09 PM](https://user-images.githubusercontent.com/18502631/203166979-5e55e0a9-d2b9-4e10-b1e9-e9a9ef9a7b32.png)

**Comment by stevenweaver** [comment]
Dear @antoine4ucsd, 

Thank you for reporting this as it's an interesting way to ensure consistency. Allow me to give a try tomorrow to see if I can replicate the same issue you are seeing before commenting further. 

Best,
Steven

**Comment by antoine4ucsd** [comment]
thank you!

**Comment by spond** [comment]
Dear @antoine4ucsd,

`bealign` does not handle **insertions** relative to the reference. So if you use HXB2_env as your reference, any insertions relative to it will be removed from the final "mapped" file (they are recorded internally, just not written to the BAM file). Because `mafft` is a general purpose MSA program, it will support such insertions. 

Best,
Sergei

**Comment by antoine4ucsd** [comment]
good to know, thank you fr the quick reply!
