### ISSUE TITLE
bealign  

### ISSUE THREAD

**Issue by spond** [veg/BioExt#7]
Somewhere in the `bealign` -> 'bam2msa' pipeline there is a bug which modifies the sequence to be aligned in an invalid way.

Input 

```
>Ref
GGGGGAATTGGAGGTTTTATCAAAGTAGGACAGTATGAT
>Qry
GGGGGAATTGGAGGTTTTATCAAAGTAAGACAGTATGAT
```

Output
```
>Qry
GGGGGAATTGGAGGTTTTATCAAAGTAG-ACAGTATGAT
``` 

Note the context around the gap is `TAG-AC` whereas the input string has `TAAGAC`. Deleting the 4th character should therefore reduce to `TAA-AC`, and deleting a character here seems like an incorrect move.

PS Turning off bam sorting makes this issue disappear (-S option)
PPS But similar issues persist in larger test files

**Comment by stevenweaver** [comment]
This issue was cause by not penalizing out of frame insertions and deletions enough

Given the following sequences : 
```
Ref : GGG|GGA|ATT|GGA|GGT|TTT|ATC|AAA|GTA|GGA|CAG|TAT|GAT
Qry : GGG|GGA|ATT|GGA|GGT|TTT|ATC|AAA|GTA|AGA|CAG|TAT|GAT
```

Resulted in :
```
Qry : GGG|GGA|ATT|GGA|GGT|TTT|ATC|AAA|GTA|G-A|CAG|TAT|GAT
```

The alignment against the reference  was
```
Qry : GGG|GGA|ATT|GGA|GGT|TTT|ATC|AAA|GTAa|G-A|CAG|TAT|GAT
```
where the lowercase `a` represents an insertion, and the hyphen represents a deletion of `G` from the reference. 

Notice that the insertion takes place in frame `9` and the deletion takes place in frame `10`. When out of frame penalties are set too low, the aligner will be predisposed to making adjacent insertion/deletions between frames. This is due to the aligner scoring a potential deleted site as a wildcard nucleotide in a frame that will minimize the score. 

The fix was to change the weight for open and deleted insertion penalties from the minimum score of a scoring matrix to the maximum between the absolution value of the minimum and maximum scores multiplied by 2.

**Comment by stevenweaver** [comment]
A fix has been tentatively committed. I will close the issue once tests are committed.
